services:
  webserver:
    build:
      context: webserver
      args:
        - URL_DOWNLOAD_ESUS=${URL_DOWNLOAD_ESUS:-https://arquivos.esusab.ufsc.br/PEC/26e603822f8adcc4/5.3.28/eSUS-AB-PEC-5.3.28-Linux64.jar}
    environment:
      - APP_DB_URL=${APP_DB_URL}
      - APP_DB_USER=${APP_DB_USER}
      - APP_DB_PASSWORD=${APP_DB_PASSWORD}
    volumes:
      - web_data:/opt/e-SUS
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    ports:
      - "${WEB_PORT:-8081}:8090"
    restart: unless-stopped
    privileged: true

volumes:
  web_data:
