services:
  database:
    build: database
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-esus}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-esus}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - esus_shared_network
    ports:
      # Expõe a porta do PostgreSQL para comunicação entre stacks
      - "${DB_PORT:-5432}:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

networks:
  esus_shared_network:
    external: true
    name: ${SHARED_NETWORK_NAME:-esus_shared_network}

volumes:
  db_data:
